# -*- coding: utf-8 -*-
"""Kalkulator kredytu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlr9VS1g4f7xtIyUp7LL0phkjISfQ-cf
"""

# Parametry wejściowe (możesz je edytować)
kwota_kredytu = 565000 # Kwota kredytu (w złotych)
oprocentowanie_roczne = 7.71  # Oprocentowanie roczne (w procentach)
maksymalna_rata = 4700 # Maksymalna miesięczna rata (w złotych)
rodzaj_raty = 'stała'  # Rodzaj raty ('stała' lub 'malejąca')
min_okres = 1  # Minimalny okres kredytowania (w latach)
max_okres = 30  # Maksymalny okres kredytowania (w latach)

# Funkcja do obliczania kredytu hipotecznego
def oblicz_kredyt_hipoteczny(kwota_kredytu, oprocentowanie_roczne, okres_kredytowania_lata, rodzaj_raty='stała'):
    liczba_rat = okres_kredytowania_lata * 12
    oprocentowanie_miesieczne = (oprocentowanie_roczne / 100) / 12
    pozostaly_kapital = kwota_kredytu
    suma_odsetek = 0

    raty = []
    splata_kapitalu = []
    splata_odsetek = []

    if rodzaj_raty == 'stała':
        rata = (kwota_kredytu * oprocentowanie_miesieczne * (1 + oprocentowanie_miesieczne) ** liczba_rat) / \
               ((1 + oprocentowanie_miesieczne) ** liczba_rat - 1)

        for _ in range(liczba_rat):
            odsetki = pozostaly_kapital * oprocentowanie_miesieczne
            kapital = rata - odsetki
            pozostaly_kapital -= kapital
            suma_odsetek += odsetki

            raty.append(rata)
            splata_kapitalu.append(kapital)
            splata_odsetek.append(odsetki)

    elif rodzaj_raty == 'malejąca':
        czesc_kapitalowa = kwota_kredytu / liczba_rat

        for _ in range(liczba_rat):
            odsetki = pozostaly_kapital * oprocentowanie_miesieczne
            rata = czesc_kapitalowa + odsetki
            pozostaly_kapital -= czesc_kapitalowa
            suma_odsetek += odsetki

            raty.append(rata)
            splata_kapitalu.append(czesc_kapitalowa)
            splata_odsetek.append(odsetki)

    else:
        raise ValueError("Nieprawidłowy rodzaj raty. Wybierz 'stała' lub 'malejąca'.")

    suma_kredytu = kwota_kredytu + suma_odsetek
    procent_kapitalu = (kwota_kredytu / suma_kredytu) * 100
    procent_odsetek = (suma_odsetek / suma_kredytu) * 100

    return {
        'raty': raty,
        'splata_kapitalu': splata_kapitalu,
        'splata_odsetek': splata_odsetek,
        'suma_odsetek': suma_odsetek,
        'suma_kredytu': suma_kredytu,
        'procent_kapitalu': procent_kapitalu,
        'procent_odsetek': procent_odsetek
    }

# Funkcja do znajdowania optymalnego okresu kredytowania
def znajdz_optymalny_okres_kredytowania(kwota_kredytu, oprocentowanie_roczne, maksymalna_rata, rodzaj_raty='stała', min_okres=1, max_okres=30):
    minimalny_koszt = float('inf')
    optymalny_okres = None
    optymalny_kredyt = None

    for okres in range(min_okres, max_okres + 1):
        kredyt = oblicz_kredyt_hipoteczny(kwota_kredytu, oprocentowanie_roczne, okres, rodzaj_raty)
        rata = kredyt['raty'][0]  # Pierwsza rata (dla raty stałej) lub najwyższa rata (dla raty malejącej)

        if rata <= maksymalna_rata:
            suma_kredytu = kredyt['suma_kredytu']

            if suma_kredytu < minimalny_koszt:
                minimalny_koszt = suma_kredytu
                optymalny_okres = okres
                optymalny_kredyt = kredyt

    if optymalny_okres is None:
        raise ValueError("Nie znaleziono okresu kredytowania, który spełnia warunek maksymalnej raty.")

    return {
        'optymalny_okres': optymalny_okres,
        'minimalny_koszt': minimalny_koszt,
        'szczegoly_kredytu': optymalny_kredyt
    }

# Obliczenia i wyświetlenie wyników
try:
    wynik = znajdz_optymalny_okres_kredytowania(kwota_kredytu, oprocentowanie_roczne, maksymalna_rata, rodzaj_raty, min_okres, max_okres)

    print("\nWyniki obliczeń:")
    print(f"Optymalny okres kredytowania: {wynik['optymalny_okres']} lat")
    print(f"Minimalny koszt kredytu: {wynik['minimalny_koszt']:.2f} zł")
    print(f"Suma odsetek: {wynik['szczegoly_kredytu']['suma_odsetek']:.2f} zł")
    print(f"Procentowy udział kapitału: {wynik['szczegoly_kredytu']['procent_kapitalu']:.2f}%")
    print(f"Procentowy udział odsetek: {wynik['szczegoly_kredytu']['procent_odsetek']:.2f}%")
    print(f"Miesięczna rata: {wynik['szczegoly_kredytu']['raty'][0]:.2f} zł")
except ValueError as e:
    print(e)